apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata: # Cluster metadata
  name: roboshop
  region: us-east-1

managedNodeGroups:
  - name: roboshop
    instanceTypes: ["m5.micro", "c3.micro", "c4.micro", "c5.micro"]
    # instanceTypes: ["m5.medium", "c3.medium","c4.medium","c5.medium"]
    desiredCapacity: 3
    spot: true # Use spot instances for cost efficiency