# ✅ ConfigMap: Environment variables for the Shipping service
apiVersion: v1
kind: ConfigMap
metadata:
  name: shipping
  namespace: roboshop
  labels:
    component: shipping
    project: roboshop
    tier: app
data:
  CART_ENDPOINT: "cart:8080"     # 🛒 Cart service endpoint
  DB_HOST: "mysql"               # 💾 MySQL database host

---
# ✅ Deployment: Manages the shipping application pods
apiVersion: apps/v1
kind: Deployment
metadata:
  name: shipping
  namespace: roboshop
  labels:                         # 🏷️ Deployment-level labels
    component: shipping
    project: roboshop
    tier: app
spec:
  replicas: 1                    # 🔁 Number of pod replicas
  selector:                      # 🎯 Match these labels to manage pods
    matchLabels:
      component: shipping
      project: roboshop
      tier: app
  template:                      # 🧱 Pod template definition
    metadata:
      labels:
        component: shipping
        project: roboshop
        tier: app
    spec:
      containers:
      - name: shipping           # 📦 Container name
        image: nagaraj411/shipping:v1   # 🖼️ Container image
        resources:               # ⚙️ Resource requests & limits
          requests:
            cpu: "100m"          # 🟡 Minimum CPU required
            memory: "256Mi"      # 🟡 Minimum memory required
          limits:
            cpu: "200m"          # 🔴 Max CPU allowed
            memory: "512Mi"      # 🔴 Max memory allowed
        envFrom:
        - configMapRef:          # 🌐 Inject env variables from ConfigMap
            name: shipping

---
# ✅ Service: Exposes the Shipping deployment internally
apiVersion: v1
kind: Service
metadata:
  name: shipping
  namespace: roboshop
  labels:
    component: shipping
    project: roboshop
    tier: app
spec:
  selector:                      # 🎯 Connect to matching pods
    component: shipping
    project: roboshop
    tier: app
  ports:
  - protocol: TCP
    port: 8080                   # 🌐 Service port
    targetPort: 8080            # 🎯 Container port

---
# ✅ HPA (HorizontalPodAutoscaler): Scales pods based on CPU
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: shipping
  namespace: roboshop
spec:
  scaleTargetRef:               # 🎯 Target Deployment
    apiVersion: apps/v1
    kind: Deployment
    name: shipping
  minReplicas: 1                # 🔽 Minimum pods
  maxReplicas: 10               # 🔼 Maximum pods
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization       # 📊 Based on CPU usage
        averageUtilization: 10  # 🎯 Target 10% CPU usage
