
apiVersion: v1
kind: ConfigMap
metadata:
  name: shipping
  namespace: roboshop
  labels:
    component: shipping
    project: roboshop
    tier: app
data:
    CART_ENDPOINT: "CART:8080"
    DB_HOST: "mysql"
---
apiVersion: apps/v1
kind: Deployment
metadata: # Deployment metadata
  name: shipping
  namespace: roboshop # Namespace for the deployment
  labels:
    component: shipping
    project: roboshop
    tier: app
    # This is the deployment for shipping
spec:
  replicas: 1 # Number of replicas
  selector:
    matchLabels:
      component: shipping
      project: roboshop
      tier: app
# this is pod definition
  template:
    metadata:
      labels:
        component: shipping
        project: roboshop
        tier: app
    spec:
      containers:
        - name: shipping
          image: nagaraj411/shipping:v1 # Shipping image
          resources:                  # 🔹 Resource configuration
            requests:
              cpu: "100m"              # 🟡 Minimum CPU required
              memory: "128Mi"         # 🟡 Minimum memory required
            limits:
              cpu: "000m"             # 🔴 Max CPU allowed
              memory: "256Mi"         # 🔴 Max memory allowed
          envFrom:
          - configMapRef:
              name: shipping # Reference to the ConfigMap
---

apiVersion: v1
kind: Service
metadata:
  name: shipping
  namespace: roboshop # Namespace for the service
  labels:
    component: shipping
    project: roboshop
    tier: app
spec:
  selector:
    component: shipping
    project: roboshop
    tier: app
  ports:
  - protocol: TCP # Protocol for the service
    port: 8080 # shipping default service port
    targetPort: 8080 # container port

---
# Horizontal Pod Autoscaler: Scale Pods Automatically
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: shipping                          # 🔹 HPA name
  namespace: roboshop
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: shipping                          # 🎯 Target: shipping deployment
  minReplicas: 1                        # 🟢 Minimum pods
  maxReplicas: 10                       # 🔺 Maximum pods
  metrics:
  - type: Resource
    resource:
      name: cpu                     # 📊 Monitored metric
      target:
        type: Utilization
        averageUtilization: 10     # 📈 Scale up if CPU > 10%