# 🔐 Secret for RabbitMQ Credentials
apiVersion: v1
kind: Secret
metadata:
  name: rabbitmq                    # 🔑 Secret name
  labels:
    component: rabbitmq            # 🧩 Identifies the component
    project: roboshop              # 📦 Project: roboshop
    tier: database                 # 🗂️ Tier: database
type: Opaque                        # 🔒 Generic key-value secret
data:
  RABBITMQ_DEFAULT_USER: "cm9ib3Nob3A="       # 👤 Username: roboshop (base64)
  RABBITMQ_DEFAULT_PASS: "cm9ib3Nob3AxMjM="   # 🔑 Password: roboshop123 (base64)

---
# 🌐 Headless Service for rabbitmq (StatefulSet DNS Discovery)
apiVersion: v1
kind: Service
metadata:
  name: rabbitmq-headless              # 🌐 Headless service name
  namespace: roboshop               # 🧭 Namespace: roboshop
  labels:
    component: rabbitmq                # 🧩 Component: rabbitmq
    project: roboshop               # 📦 Project label
    tier: database                  # 🗂️ Tier: Database
spec:
  clusterIP: None                   # ❌ No ClusterIP → Headless for stable DNS
  selector:
    component: rabbitmq
    project: roboshop
    tier: database
  ports:
  - protocol: TCP
    port: 5672                      # 🚪 rabbitmq default port (Service)
    targetPort: 5672                # 🎯 Matches container port

---
# 📡 ClusterIP Service for rabbitmq access
apiVersion: v1
kind: Service
metadata:
  name: rabbitmq                       # 📡 Standard ClusterIP service
  namespace: roboshop
  labels:
    component: rabbitmq
    project: roboshop
    tier: database
spec:
  selector:
    component: rabbitmq
    project: roboshop
    tier: database
  ports:
  - protocol: TCP
    port: 5672                      # 🚪 Port exposed to clients
    targetPort: 5672                # 🎯 Container’s internal port
---
# 🏗️ rabbitmq StatefulSet with EBS-based Persistent Volumes
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: rabbitmq
  namespace: roboshop
  labels:
    component: rabbitmq
    project: roboshop
    tier: database
spec:
  selector:
    matchLabels:
      component: rabbitmq
      project: roboshop
      tier: database               # 🧬 Must match pod template labels
  serviceName: "rabbitmq-headless"    # 🔁 Required for stable network ID
  replicas: 2                      # 🧍🧍 Creates 2 rabbitmq pods
  template:
    metadata:
      labels:
        component: rabbitmq
        project: roboshop
        tier: database
    spec:
      containers:
      - name: rabbitmq
        image: rabbitmq:3          # 🐳 rabbitmq official image
        envFrom:
        - secretRef:
            name: rabbitmq          # 🔑 Reference to the secret for credentials
        volumeMounts:
        - name: rabbitmq-data
          mountPath: /var/lib/rabbitmq   # 💾 Mount rabbitmq data directory
  volumeClaimTemplates:
  - metadata:
      name: rabbitmq-data             # 📦 PVC name template
    spec:
      accessModes: [ "ReadWriteOnce" ]  # ✍️ Single node write access
      storageClassName: "roboshop-ebs"  # 📀 EBS-backed storage class
      resources:
        requests:
          storage: 2Gi             # 💽 2Gi per rabbitmq pod