---
apiVersion: v1
kind: Service  # 🔧 Defines a Service
metadata:
  name: mongodb-headless  # 🏷️ Name of the headless service
  namespace: roboshop  # 📂 Namespace where service runs
  labels:  # 🏷️ Used for identifying and selecting
    component: mongodb
    project: roboshop
    tier: database
spec:
  clusterIP: None  # 🚫 No clusterIP (makes it headless)
  selector:  # 🔍 Used to find matching Pods
    component: mongodb
    project: roboshop
    tier: database
  ports:
  - protocol: TCP
    port: 27017  # 🌐 Port exposed by the service
    targetPort: 27017  # 🎯 Port on the container

---
apiVersion: v1
kind: Service  # 🔧 Standard ClusterIP service
metadata:
  name: mongodb  # 🏷️ Name of the service
  namespace: roboshop
  labels:
    component: mongodb
    project: roboshop
    tier: database
spec:
  selector:  # 🔍 Matches Pods using these labels
    component: mongodb
    project: roboshop
    tier: database
  ports:
  - protocol: TCP
    port: 27017  # 🌐 Port clients will connect to
    targetPort: 27017  # 🎯 Port on the container
---
apiVersion: apps/v1
kind: StatefulSet  # 🧱 Manages stateful Pods with identity
metadata:
  name: mongodb
  namespace: roboshop
  labels:
    component: mongodb
    project: roboshop
    tier: database
spec:
  selector:
    matchLabels:  # 🧩 Must match Pod template labels
      component: mongodb
      project: roboshop
      tier: database
  serviceName: "mongodb-headless"  # 🔗 Connects to headless service
  replicas: 3  # 🔁 Number of MongoDB instances
  template:
    metadata:
      labels:  # 🏷️ Labels for Pods
        component: mongodb
        project: roboshop
        tier: database
    spec:
      containers:
      - name: mongodb
        image: nagaraj411/mongodb:v1  # 📦 MongoDB Docker image
        volumeMounts:
        - name: mongodb-data
          mountPath: /data/db  # 💾 Data location in container
  volumeClaimTemplates:  # 📦 Template to create PVC per replica
  - metadata:
      name: mongodb-data
    spec:
      accessModes: [ "ReadWriteOnce" ]  # 📝 Access type
      storageClassName: "roboshop-ebs"  # 🗂️ EBS-backed StorageClass
      resources:
        requests:
          storage: 2Gi  # 📏 Disk size requested