# ConfigMap: App Environment Variables
apiVersion: v1
kind: ConfigMap
metadata:
  name: catalogue                    # ðŸ”¹ ConfigMap name
  namespace: roboshop               # ðŸ”¹ Namespace for scope
  labels:                           # ðŸ”¹ Labels for identification
    component: catalogue
    project: roboshop
    tier: app
data:                               # ðŸ”¹ Key-value pairs used in the app
  MONGO: "true"
  MONGO_URL: "mongodb://mongodb:27017/catalogue"
---
# Deployment: Create & Manage Pods
apiVersion: apps/v1
kind: Deployment
metadata:
  name: catalogue                   # ðŸ”¹ Deployment name
  namespace: roboshop
  labels:
    component: catalogue
    project: roboshop
    tier: app
spec:
  replicas: 1                       # ðŸ”¹ Initial number of pod replicas
  selector:
    matchLabels:                    # ðŸ”¹ Matches pods with same labels
      component: catalogue
      project: roboshop
      tier: app
  template:
    metadata:
      labels:                       # ðŸ”¹ Pod labels
        component: catalogue
        project: roboshop
        tier: app
    spec:
      containers:
      - name: catalogue             # ðŸ”¹ Container name
        image: nagaraj411/catalogue:v1   # ðŸ“¦ Custom container image
        resources:                  # ðŸ”¹ Resource configuration
          requests:
            cpu: "50m"              # ðŸŸ¡ Minimum CPU required
            memory: "128Mi"         # ðŸŸ¡ Minimum memory required
          limits:
            cpu: "100m"             # ðŸ”´ Max CPU allowed
            memory: "256Mi"         # ðŸ”´ Max memory allowed
        envFrom:
        - configMapRef:
            name: catalogue         # ðŸ”— Inject env from ConfigMap
---
# Service: Expose the Deployment
apiVersion: v1
kind: Service
metadata:
  name: catalogue                   # ðŸ”¹ Service name
  namespace: roboshop
  labels:
    component: catalogue
    project: roboshop
    tier: app
spec:
  selector:                         # ðŸ” Matches pods by label
    component: catalogue
    project: roboshop
    tier: app
  ports:
    - protocol: TCP                 # ðŸ”Œ Protocol
      port: 8080                    # ðŸŒ Service port
      targetPort: 8080             # ðŸŽ¯ Container port
---
# Horizontal Pod Autoscaler: Scale Pods Automatically
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: catalogue                   # ðŸ”¹ HPA name
  namespace: roboshop
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: catalogue                 # ðŸŽ¯ Target: catalogue deployment
  minReplicas: 1                    # ðŸŸ¢ Minimum pods
  maxReplicas: 10                   # ðŸ”º Maximum pods
  metrics:
  - type: Resource
    resource:
      name: cpu                     # ðŸ“Š Monitored metric
      target:
        type: Utilization
        averageUtilization: 10     # ðŸ“ˆ Scale up if CPU > 10%
