# 🌐 Headless Service for Redis (StatefulSet DNS Discovery)
apiVersion: v1
kind: Service
metadata:
  name: redis-headless              # 🌐 Headless service name
  namespace: roboshop               # 🧭 Namespace: roboshop
  labels:
    component: redis                # 🧩 Component: Redis
    project: roboshop               # 📦 Project label
    tier: database                  # 🗂️ Tier: Database
spec:
  clusterIP: None                   # ❌ No ClusterIP → Headless for stable DNS
  selector:
    component: redis
    project: roboshop
    tier: database
  ports:
  - protocol: TCP
    port: 6379                      # 🚪 Redis default port (Service)
    targetPort: 6379                # 🎯 Matches container port

---
# 📡 ClusterIP Service for Redis access
apiVersion: v1
kind: Service
metadata:
  name: redis                       # 📡 Standard ClusterIP service
  namespace: roboshop
  labels:
    component: redis
    project: roboshop
    tier: database
spec:
  selector:
    component: redis
    project: roboshop
    tier: database
  ports:
  - protocol: TCP
    port: 6379                      # 🚪 Port exposed to clients
    targetPort: 6379                # 🎯 Container’s internal port
---
# 🏗️ Redis StatefulSet with EBS-based Persistent Volumes
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: redis
  namespace: roboshop
  labels:
    component: redis
    project: roboshop
    tier: database
spec:
  selector:
    matchLabels:
      component: redis
      project: roboshop
      tier: database               # 🧬 Must match pod template labels
  serviceName: "redis-headless"    # 🔁 Required for stable network ID
  replicas: 2                      # 🧍🧍 Creates 2 Redis pods
  template:
    metadata:
      labels:
        component: redis
        project: roboshop
        tier: database
    spec:
      containers:
      - name: redis
        image: redis:7.0           # 🐳 Redis official image
        volumeMounts:
        - name: redis-data
          mountPath: /data         # 💾 Mount Redis data directory
  volumeClaimTemplates:
  - metadata:
      name: redis-data             # 📦 PVC name template
    spec:
      accessModes: [ "ReadWriteOnce" ]  # ✍️ Single node write access
      storageClassName: "roboshop-ebs"  # 📀 EBS-backed storage class
      resources:
        requests:
          storage: 2Gi             # 💽 2Gi per Redis pod